default_platform(:android)

platform :android do
  private_lane :setup_variables do
    PACKAGE_NAME = ENV["PACKAGE_NAME"]
    BUILD_NUMBER_PATH = ENV["BUILD_NUMBER_PATH"]
    KEYSTORE_PATH = ENV['KEYSTORE_PATH']
    KEYSTORE_PASSWORD = ENV['KEYSTORE_PASSWORD']
    KEYSTORE_ALIAS = ENV['KEYSTORE_ALIAS']
    KEYSTORE_ALIAS_PASSWORD = ENV['KEYSTORE_ALIAS_PASSWORD']
    JSON_KEY_PATH = ENV['JSON_KEY_PATH']
  end

  before_all do
    setup_variables
  end

  lane :release do |options|
     sh "flutter pub get"
     sh "flutter build apk --release"
  end
end