default_platform(:android)

platform :android do
  private_lane :setup_variables do
    PACKAGE_NAME = ENV["PACKAGE_NAME"]
    BUILD_NUMBER_PATH = ENV["BUILD_NUMBER_PATH"]
    KEYSTORE_PATH = ENV['KEYSTORE_PATH']
    KEYSTORE_PASSWORD = ENV['KEYSTORE_PASSWORD']
    KEYSTORE_ALIAS = ENV['KEYSTORE_ALIAS']
    KEYSTORE_ALIAS_PASSWORD = ENV['KEYSTORE_ALIAS_PASSWORD']
    JSON_KEY_PATH = ENV['JSON_KEY_PATH']
  end

  before_all do
    setup_variables
  end

  lane :release do |options|
     sh "flutter pub get"
     sh "flutter build appbundle --release"
      puts "Current Directory: /android"
     upload_to_play_store(
           release_status: "draft",
           json_key: "../build/app/outputs/bundle/release/app-release.aab", #JSON_KEY_PATH
           track: "internal",
           package_name: "com.example.ci_cd_demo",
           aab: "../build/app/outputs/bundle/release/app-release.aab",
           skip_upload_metadata: true,
           skip_upload_images: true,
           skip_upload_screenshots: true,
           skip_upload_apk: true
         )
  end
end