default_platform(:ios)

platform :ios do
  private_lane :setup_variables do
    PACKAGE_NAME = ENV["PACKAGE_NAME"]
    APPSTORE_CONNECT_API_KEY_BASE64 = ENV['APP_STORE_CONNECT_API_KEY']
    APP_BUNDLE_ID = ENV['APP_BUNDLE_ID']
    APP_STORE_API_KEY_ID = ENV['APP_STORE_API_KEY_ID']
    APP_STORE_API_ISSUER_ID = ENV['APP_STORE_API_ISSUER_ID']
    TEAM_ID = ENV['TEAM_ID']
    TEAM_NAME = ENV['TEAM_NAME']
  end

  before_all do
    setup_variables
  end

  lane :release do |options|
    # sh 'flutter clean'
    # sh 'flutter pub get'
    # sh 'pod install'
    # sh 'flutter build ios --release'
    Dir.chdir("..") do

        # sh 'xcodebuild -workspace Runner.xcworkspace \
        #      -scheme Runner clean archive -configuration release \
        #      -sdk iphoneos -archivePath Runner.xcarchive'

        #sh 'xcodebuild -exportArchive -archivePath  Runner.xcarchive \
        #      -exportOptionsPlist  exportOptions.plist \
        #      -exportPath  cicdapp.ipa'

        app_store_connect_api_key(
              key_id: "#{APP_STORE_API_KEY_ID}",
              issuer_id: "#{APP_STORE_API_ISSUER_ID}",
              key_content: "-----BEGIN PRIVATE KEY-----
                            MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgyQt7vTv5wdQ/3B7s
                            r60W6AKRsmr4Zwf1rPa+yt5mZvugCgYIKoZIzj0DAQehRANCAAT71FWxS080XYBZ
                            aaAALku3wDISB/RVpQxhqn+vcsVSS8q8Boo7ybYGBWqJ8ZHWiahRySoTKACsmRiU
                            3HdNBRU3
                            -----END PRIVATE KEY-----", # "#{APPSTORE_CONNECT_API_KEY_BASE64}",
              #key_filepath: "fastlane/app_store_connect_api_key.p8",
            )

        sync_code_signing(type: "appstore", readonly: true)

        upload_to_testflight(
            app_identifier: APP_BUNDLE_ID,
            ipa: '../build/ios/ipa/cicdapp.ipa',
            changelog: 'Test the build and report the bugs.',
            team_id: TEAM_ID,
            team_name: TEAM_NAME
        )
    end
  end
end