default_platform(:ios)

platform :ios do
  private_lane :setup_variables do
    PACKAGE_NAME = ENV["PACKAGE_NAME"]
    APPSTORE_CONNECT_API_KEY_BASE64 = ENV['APP_STORE_CONNECT_API_KEY']
    APP_BUNDLE_ID = ENV['APP_BUNDLE_ID']
    TEAM_ID = ENV['TEAM_ID']
    TEAM_NAME = ENV['TEAM_NAME']
  end

  before_all do
    setup_variables
  end

  lane :release do |options|
    sh 'flutter clean'
    sh 'flutter pub get'
    sh 'pod install'
    # sh 'flutter build ios --release'
    sh 'ls'
    Dir.chdir("..") do
        sh 'ls'

        sh 'xcodebuild -workspace Runner.xcworkspace \
              -scheme Runner clean archive -configuration release \
              -sdk iphoneos -archivePath Runner.xcarchive'

        sh 'xcodebuild -exportArchive -archivePath  Runner.xcarchive \
              -exportOptionsPlist  exportOptions.plist \
              -exportPath  cicdapp.ipa'

        app_store_connect_api_key(
              key_id: APP_STORE_API_KEY_ID,
              issuer_id: APP_STORE_API_ISSUER_ID,
              key_content: APPSTORE_CONNECT_API_KEY_BASE64,
              #key_filepath: "fastlane/app_store_connect_api_key.p8",
            )

        sync_code_signing(type: "appstore", readonly: true)

        upload_to_testflight(
            app_identifier: APP_BUNDLE_ID,
            ipa: '../build/ios/ipa/cicdapp.ipa',
            changelog: 'Test the build and report the bugs.',
            team_id: TEAM_ID,
            team_name: TEAM_NAME
        )
    end
  end
end