# Fastlane script is written in Ruby script language
default_platform(:android)

platform :android do
  private_lane :setup_variables do
    PACKAGE_NAME = ENV["PACKAGE_NAME"]
    BUILD_NUMBER_PATH = ENV["BUILD_NUMBER_PATH"]
    KEYSTORE_PATH = ENV['KEYSTORE_PATH']
    KEYSTORE_PASSWORD = ENV['KEYSTORE_PASSWORD']
    KEYSTORE_ALIAS = ENV['KEYSTORE_ALIAS']
    KEYSTORE_ALIAS_PASSWORD = ENV['KEYSTORE_ALIAS_PASSWORD']
    JSON_KEY_PATH = ENV['JSON_KEY_PATH']
    SLACK_WEBHOOK = ENV['SLACK_WEBHOOK']
  end

  before_all do
    setup_variables
  end

  lane :release do |options|
     verifyPlayConsoleConnection

     sh "flutter pub get"
     sh "flutter build appbundle --release"
     puts "Current Directory: /android"
     version = flutter_version()

     upload_to_play_store(
           release_status: "draft",
           json_key: JSON_KEY_PATH,
           track: "internal",
           package_name: PACKAGE_NAME,
           aab: "../build/app/outputs/bundle/release/app-release.aab",
           #skip_upload_metadata: true,
           skip_upload_images: true,
           skip_upload_screenshots: true,
           skip_upload_apk: true,
           version_code: version["version_code"], # From pubspec.yaml
           version_name: version["version_name"]
         )

         notify_channel
  end

  lane :verifyPlayConsoleConnection do
     validate_play_store_json_key(
       json_key: JSON_KEY_PATH
     )
  end

  lane :notify_channel do
     slack(
               message: "CI CD Demo Android App upload on the Play Store for internal testing!",
               #channel: "#channel",  # Optional, by default will post to the default channel configured for the POST URL.
               success: true,        # Optional, defaults to true.
               slack_url: SLACK_WEBHOOK,
               payload: {  # Optional, lets you specify any number of your own Slack attachments.
                 "Build Date" => Time.new.to_s,
                 "Built by" => "Jenkins",
               },
             )
  end
end