name: Build App and Distribute it on PlayStore and AppStore

on:
  pull_request:
    branches:
      - release/beta

  push:
    branches:
      - release/beta

jobs:

  distribute-ipa:
    runs-on: macos-latest
    needs: build-ios
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: List files in the repository before
        run: ls -la

      - run: cd ios

      - name: List files in the repository after
        run: ls -la

      # AppStore Distribution
      - name: Publish iOS Application to Appstore
        # You may pin to the exact commit or the version.
        # uses: UmutSERIFLER/publish-ios-appstore@c0c2e859225ed6f0c9ebb206b2657eea8a5f7c9a
        uses: UmutSERIFLER/publish-ios-appstore@1.0.1
        with:
          # Project name is an input that will be used for action
          projectName: "Runner"
          # Encrypted certificate Base64
          certificateBase64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          # Password is used for p12
          p12FilePassword: ${{ secrets.P12_PASSWORD }}
          # Provision Profile is encrypted Base64
          provisionProfileBase64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          # Keychain Password to save p12 file
          keychainPassword: ${{ secrets.KEYCHAIN_PASSWORD }}
          # AppStore API Key to upload app
          appstoreAPIKey: ${{ secrets.APP_STORE_API_KEY }}
          # AppStore API Key ID to upload app
          appstoreAPIKeyID: ${{ secrets.APP_STORE_API_KEY_ID }}
          # AppStore API Key Issuer to upload app
          appstoreAPIIssuer: ${{ secrets.APP_STORE_ISSUER_ID }}
          # Team ID for app group
          teamID: ${{ secrets.IOS_TEAM_ID }}
          # Mobile Provision Name
          mobileProvision: ${{ secrets.PROVISION_PROFILE }}

  notify-team:
    runs-on: macos-latest
    needs:
      - distribute-ipa
    steps:
      - name: Send to Slack
        # You may pin to the exact commit or the version.
        # uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d
        uses: slackapi/slack-github-action@v2.0.0
        with:
          # If the step exits with an error on errors or continues.
          errors: true # optional, default is false
          # The Slack API method to call.
          method: "chat.postMessage" # optional
          # Attributes that create the content of the request using JSON or YAML.
          # payload-file-path: ".github/slack_payload.json" # optional
          token: ${{ secrets.SLACK_BOT_TOKEN }} # optional
          payload: |
            channel: "${{ secrets.SLACK_CHANNEL_ID }}"
            text: "Hello Team, Android and iOS apps available on the PlayStore and AppStore for testing."
