name: Build App and Distribute it on PlayStore and AppStore

on:
  pull_request:
    branches:
      - release/beta

  push:
    branches:
      - release/beta

jobs:

  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Basic Setup via Composite
        uses: ./.github/action_basic_setup

      - name: Initialize Keychain
        run: keychain initialize

      - name: Create a directory for certificate key
        run: mkdir certificates
        working-directory: ios

      - name: Fetch Signing Profile
        working-directory: ios
        run: app-store-connect fetch-signing-files com.codknox.cicddemo \
          --platform IOS \
          --type IOS_APP_STORE \
          --certificate-key= /certificates \
          --create

      - name: Add Certificates to the Keychain
        run: keychain add-certificates

      - name: Update XCode to use signing profile
        run: xcode-project use-profiles

      - name: Fetch plugins Flutter Project
        run: flutter pub get
        shell: bash
