name: Build App and Distribute it via Firebase

on:
  pull_request:
    branches:
      - release/firebase

  push:
    branches:
      - release/firebase

jobs:
  build-android:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Basic Setup via Composite
        uses: ./.github/action_basic_setup

      - name: Build Android App
        uses: ./.github/action_build_android_app

      - name: Upload Android App
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: "build/app/outputs/flutter-apk/app-release.apk"

  distribute:
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download a Android APK
        uses: actions/download-artifact@v4.1.8
        with:
          # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
          name: "app-release.apk" # "app-release.apk" # optional
          # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
          path: ".github/artifacts/" # optional
          # A glob pattern matching the artifacts that should be downloaded. Ignored if name is specified.
          # pattern: # optional
          # When multiple artifacts are matched, this changes the behavior of the destination directories. If true, the downloaded artifacts will be in the same directory specified by path. If false, the downloaded artifacts will be extracted into individual named directories within the specified path.
          # merge-multiple: # optional, default is false
          # The GitHub token used to authenticate with the GitHub API. This is required when downloading artifacts from a different repository or from a different workflow run. If this is not specified, the action will attempt to download artifacts from the current repository and the current workflow run.
          # github-token: # optional
          # The repository owner and the repository name joined together by "/". If github-token is specified, this is the repository that artifacts will be downloaded from.
          # repository: # optional, default is ${{ github.repository }}
          # The id of the workflow run where the desired download artifact was uploaded from. If github-token is specified, this is the run that artifacts will be downloaded from.
          # run-id: # optional, default is ${{ github.run_id }}

      - name: List downloaded artifacts
        run: ls -la .github/artifacts
        shell: bash

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: "1:296310144448:android:7e312254b40b06f99d5c25"
          # Content of service credentials file

          # Important: Repository `secrets` can only be accessed in the main workflow file
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }} # optional
          # Artifact to upload (.apk or .ipa)
          file: ".github/artifacts/app-release.apk"
          # file: "build/app/outputs/flutter-apk/app-release.apk"
          # Distribution groups
          groups: "codknox-testers" # optional
          # Distribution testers
          releaseNotes: "Test the core features of the app v(1.0.${{ github.run_number }})" # optional
          # Flag that can included to print verbose log output.
          debug: true

    #Job 3
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Basic Setup via Composite
        uses: ./.github/action_basic_setup

      - name: Set Up CocoaPods
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer          
          cd ios 
            if [ -f "Podfile" ]; then echo "Podfile exists."; else pod init; fi
            pod deintegrate
            pod install
            pod update

      - name: Install Profile
        uses: nickwph/apple-build-certificate-action@v1
        with:
          certificate-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.P12_PASSWORD }}

      - uses: nickwph/apple-provisioning-profile-action@v1   # Optional: Recommend to use with apple-provisioning-profile-action
        with:
          profile-base64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}

      - name: Build iOS
        run: flutter build ios

      - name: Export Archive
        run: flutter build ipa --release
        working-directory: ./

      - run: mkdir Payload
        working-directory: build/ios/archive/Runner.xcarchive/Products/Applications

      - run: mv Runner.app/ Payload
        working-directory: build/ios/archive/Runner.xcarchive/Products/Applications

      - run: ls -R build/ios/archive/Runner.xcarchive/Products/Applications/Payload

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/archive/Runner.xcarchive/Products/Applications

#      - name: Validate IPA
#        run: codesign -vvv --deep --strict FlutterIpaExport.ipa
#        working-directory: build/ios/archive/Runner.xcarchive/Products/Applications

      - name: Upload ipa on Repository Environment
        uses: actions/upload-artifact@v4
        with:
          name: ci_cd_demo.ipa
          path: "build/ios/archive/Runner.xcarchive/Products/Applications/FlutterIpaExport.ipa"
          #path: "build/ios/ipa/ci_cd_demo.ipa"

    # Job 4 (Depends upon Job 3)
  distribute-ipa:
    runs-on: ubuntu-latest
    needs: build-ios
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download ipa artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: "ci_cd_demo.ipa"
          path: ".github/artifacts/"

      - name: List Download Artifacts
        run: ls -la .github/artifacts/

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: "1:296310144448:ios:824ada3de2e7f3679d5c25"

          # Content of service credentials file
          # Important: Repository `secrets` can only be accessed in the main workflow file
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }} # optional
          # Artifact to upload (.apk or .ipa)
          file: ".github/artifacts/FlutterIpaExport.ipa"
          # Distribution groups
          groups: "codknox-testers" # optional
          # Distribution testers
          releaseNotes: "Test the core features of the app v(1.0.${{ github.run_number }})" # optional
          # Flag that can included to print verbose log output.
          debug: true

  notify-team:
    runs-on: macos-latest
    needs:
      - distribute
      - distribute-ipa
    steps:
      - name: Send to Slack
        # You may pin to the exact commit or the version.
        # uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d
        uses: slackapi/slack-github-action@v2.0.0
        with:
          # If the step exits with an error on errors or continues.
          errors: true # optional, default is false
          # The Slack API method to call.
          method: "chat.postMessage" # optional
          # Attributes that create the content of the request using JSON or YAML.
          # payload-file-path: ".github/slack_payload.json" # optional
          token: ${{ secrets.SLACK_BOT_TOKEN }} # optional
          payload: |
            channel: "${{ secrets.SLACK_CHANNEL_ID }}"
            text: "Hello Team, Android and iOS apps available on the Firebase Distribution app for testing."

