name: Build App and Distribute it via Firebase

on:
  pull_request:
    branches:
      - release/firebase

  push:
    branches:
      - release/firebase

jobs:


  notify-team:
    runs-on: macos-latest
#    needs:
#      - distribute
#      - distribute-ipa
    steps:
      - name: Send to Slack
        # You may pin to the exact commit or the version.
        # uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d
        uses: slackapi/slack-github-action@v2.0.0
        with:
          # If the step exits with an error on errors or continues.
          errors: true # optional, default is false
          # The Slack API method to call.
          method: "chat.postMessage" # optional
          # Attributes that create the content of the request using JSON or YAML.
          # payload-file-path: ".github/slack_payload.json" # optional
          token: ${{ secrets.SLACK_BOT_TOKEN }} # optional
          payload: |
            channel: "C07APA3KV8W"
            text: "Break"
