name: Build App and Distribute it on PlayStore and AppStore

on:
  pull_request:
    branches:
      - release/beta

  push:
    branches:
      - release/beta

jobs:

  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Basic Setup via Composite
        uses: ./.github/action_basic_setup

      - name: Install Profile
        uses: nickwph/apple-build-certificate-action@v1
        with:
          certificate-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.P12_PASSWORD }}

      - uses: nickwph/apple-provisioning-profile-action@v1   # Optional: Recommend to use with apple-provisioning-profile-action
        with:
          profile-base64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}

      - name: Update XCode to use signing profile
        run: xcode-project use-profiles

      - name: Fetch plugins Flutter Project
        run: flutter pub get
        shell: bash

      - name: Build iOS
        run: flutter build ios

      - name: Export Archive
        run: flutter build ipa --release
        working-directory: ./

      - run: mkdir Payload
        working-directory: build/ios/archive/Runner.xcarchive/Products/Applications

      - run: mv Runner.app/ Payload
        working-directory: build/ios/archive/Runner.xcarchive/Products/Applications

      - run: ls -R build/ios/archive/Runner.xcarchive/Products/Applications/Payload

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/archive/Runner.xcarchive/Products/Applications

      - name: Validate IPA
        run: codesign -vvv --deep --strict FlutterIpaExport.ipa
        working-directory: build/ios/archive/Runner.xcarchive/Products/Applications

