name: Build App and Distribute it on PlayStore and AppStore

on:
  pull_request:
    branches:
      - release/beta

  push:
    branches:
      - release/beta

jobs:
  build-android:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Basic Setup via Composite
        uses: ./.github/action_basic_setup

      - name: Build Android App
        uses: ./.github/action_build_android_app

      - name: Upload Android App
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: "build/app/outputs/flutter-apk/app-release.apk"

  distribute:
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download a Android APK
        uses: actions/download-artifact@v4.1.8
        with:
          # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
          name: "app-release.apk" # "app-release.apk" # optional
          # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
          path: ".github/artifacts/" # optional
          # A glob pattern matching the artifacts that should be downloaded. Ignored if name is specified.
          # pattern: # optional
          # When multiple artifacts are matched, this changes the behavior of the destination directories. If true, the downloaded artifacts will be in the same directory specified by path. If false, the downloaded artifacts will be extracted into individual named directories within the specified path.
          # merge-multiple: # optional, default is false
          # The GitHub token used to authenticate with the GitHub API. This is required when downloading artifacts from a different repository or from a different workflow run. If this is not specified, the action will attempt to download artifacts from the current repository and the current workflow run.
          # github-token: # optional
          # The repository owner and the repository name joined together by "/". If github-token is specified, this is the repository that artifacts will be downloaded from.
          # repository: # optional, default is ${{ github.repository }}
          # The id of the workflow run where the desired download artifact was uploaded from. If github-token is specified, this is the run that artifacts will be downloaded from.
          # run-id: # optional, default is ${{ github.run_id }}

      - name: List downloaded artifacts
        run: ls -la .github/artifacts
        shell: bash

      # PlayStore Distribution

  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Basic Setup via Composite
        uses: ./.github/action_basic_setup

      - name: Install gpg
        run: brew install gnupg

      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.APPLEID_PASSPHRASE }}
        run: ./.github/scripts/decrypt_secrets.sh

      - name: Fetch plugins Flutter Project
        run: flutter pub get
        shell: bash

      - name: Set Up CocoaPods
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer          
          cd ios 
            if [ -f "Podfile" ]; then echo "Podfile exists."; else pod init; fi
            pod deintegrate
            pod install
            pod update

      - name: Archiving project
        run: ./.github/scripts/archive_app.sh

      - name: Exporting .ipa
        run: ./.github/scripts/export_ipa.sh

      - name: Publishing app
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLE_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        run: ./.github/scripts/publish_testflight.sh


  notify-team:
    runs-on: macos-latest
    needs:
      - build-ios
      #- distribute-ipa
    steps:
      - name: Send to Slack
        # You may pin to the exact commit or the version.
        # uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d
        uses: slackapi/slack-github-action@v2.0.0
        with:
          # If the step exits with an error on errors or continues.
          errors: true # optional, default is false
          # The Slack API method to call.
          method: "chat.postMessage" # optional
          # Attributes that create the content of the request using JSON or YAML.
          # payload-file-path: ".github/slack_payload.json" # optional
          token: ${{ secrets.SLACK_BOT_TOKEN }} # optional
          payload: |
            channel: "${{ secrets.SLACK_CHANNEL_ID }}"
            text: "Hello Team, Android and iOS apps available on the PlayStore and AppStore for testing."
