name: Build App and Distribute it via Firebase

on:
  pull_request:
    branches:
      - release/firebase

  push:
    branches:
      - release/firebase

jobs:

  #Job 3
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Basic Setup via Composite
        uses: ./.github/action_basic_setup

      - run: cd ios
      - run: pwd
      #- run: pod deintegrate
      - run: pod install
      - run: pod update
      - run: cd ..

      - name: Build iOS App
        run: flutter build ipa --release --no-codesign

      - name: Upload ipa on Repository Environment
        uses: actions/upload-artifact@v4
        with:
          name: ci_cd_demo.ipa
          path: "build/ios/ipa/ci_cd_demo.ipa"

  # Job 4 (Depends upon Job 3)
  distribute-ipa:
    runs-on: ubuntu-latest
    needs: build-ios
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download ipa artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: "ci_cd_demo.ipa"
          path: ".github/artifacts/"

      - name: List Download Artifacts
        run: ls -la .github/artifacts/

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: "1:296310144448:ios:d49519a2e3b5b43c9d5c25"

          # Content of service credentials file
          # Important: Repository `secrets` can only be accessed in the main workflow file
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }} # optional
          # Artifact to upload (.apk or .ipa)
          file: ".github/artifacts/ci_cd_demo.ipa"
          # Distribution groups
          groups: "codknox-testers" # optional
          # Distribution testers
          releaseNotes: "Test the core features of the app v(1.0.${{ github.run_number }})" # optional
          # Flag that can included to print verbose log output.
          debug: true


