name: Build App and Distribute it via Firebase

on:
  pull_request:
    branches:
      - release/firebase

  push:
    branches:
      - release/firebase

jobs:
  build-android:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Basic Setup via Composite
        uses: ./.github/action_basic_setup

      - name: Build Android App
        uses: ./.github/action_build_android_app

  distribute:
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: "1:296310144448:android:7e312254b40b06f99d5c25"
          # Content of service credentials file

          # Important: Repository `secrets` can only be accessed in the main workflow file
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }} # optional
          # Artifact to upload (.apk or .ipa)
          # file: ".github/artifacts/app-release.apk"
          file: "build/app/outputs/flutter-apk/app-release.apk"
          # Distribution groups
          groups: "codknox-testers" # optional
          # Distribution testers
          releaseNotes: "Test the core features of the app v(1.0.${{ github.run_number }})" # optional
          # Flag that can included to print verbose log output.
          debug: true





