name: Build App and Distribute it on PlayStore and AppStore

on:
  pull_request:
    branches:
      - release/beta

  push:
    branches:
      - release/beta

jobs:

  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Basic Setup via Composite
        uses: ./.github/action_basic_setup

      - name: Install gpg
        run: brew install gnupg

      - name: Grant execute permission for decrypt_secrets.sh
        run: chmod +x ./.github/scripts/decrypt_secrets.sh

      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.APPLEID_PASSPHRASE }}
        run: ./.github/scripts/decrypt_secrets.sh

      - name: Fetch plugins Flutter Project
        run: flutter pub get
        shell: bash

      - name: Set Up CocoaPods
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer          
          cd ios 
            if [ -f "Podfile" ]; then echo "Podfile exists."; else pod init; fi
            pod deintegrate
            pod install
            pod update

      - name: Archiving project
        run: |
          git update-index --chmod=+x ./.github/scripts/archive_app.sh
          ./.github/scripts/archive_app.sh

      - name: Exporting .ipa
        run: |
          git update-index --chmod=+x ./.github/scripts/export_ipa.sh
          ./.github/scripts/export_ipa.sh

      - name: Publishing app
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLE_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        run: |
          git update-index --chmod=+x ./.github/scripts/publish_testflight.sh
          ./.github/scripts/publish_testflight.sh


  notify-team:
    runs-on: macos-latest
    needs:
      - build-ios
      #- distribute-ipa
    steps:
      - name: Send to Slack
        # You may pin to the exact commit or the version.
        # uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d
        uses: slackapi/slack-github-action@v2.0.0
        with:
          # If the step exits with an error on errors or continues.
          errors: true # optional, default is false
          # The Slack API method to call.
          method: "chat.postMessage" # optional
          # Attributes that create the content of the request using JSON or YAML.
          # payload-file-path: ".github/slack_payload.json" # optional
          token: ${{ secrets.SLACK_BOT_TOKEN }} # optional
          payload: |
            channel: "${{ secrets.SLACK_CHANNEL_ID }}"
            text: "Hello Team, Android and iOS apps available on the PlayStore and AppStore for testing."
