name: Build and Analyze

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - pipeline

jobs:
  build-android:
    runs-on: macos-latest

    steps:
      - name: "Code Checkout"
        uses: actions/checkout@v1

      - name: Basic Setup via Composite
        uses: ./.github/action_basic_setup

      - name: Build Android App
        uses: ./.github/action_build_android_app

#      - name: Upload Android App to the Repository
#        uses: ./.github/action_upload_build_to_repo

  distribute:
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - name: Distribute build on the Firebase
        uses: ./.github/action_distribute_build_on_firebase





