name: Build and Analyze

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - pipeline

jobs:
  build-android:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.27.3'

      - name: Fetch plugins Flutter Project
        run: flutter pub get

      - name: Build Android App
        run: flutter build apk --release

      - name: Upload Android App
        uses: actions/upload-artifact@v4
        with:
          name: uploaded-android-app.apk
          path: "build/app/outputs/flutter-apk/app-release.apk"

#      - name: Push Releases to Github Repo
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
#          tag: v1.0.${{ github.run_number }}
#          commit: pipeline #This should be the same branch for which the workflow is running
#          token: ${{ secrets.TOKEN }}

  distribute:
    runs-on: ubuntu-latest
    needs: build-android
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download a Android APK
        uses: actions/download-artifact@v4.1.8
        with:
          # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
          name: "uploaded-android-app.apk" # "app-release.apk" # optional
          # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
          path: ".github/artifacts/" # optional
          # A glob pattern matching the artifacts that should be downloaded. Ignored if name is specified.
          # pattern: # optional
          # When multiple artifacts are matched, this changes the behavior of the destination directories. If true, the downloaded artifacts will be in the same directory specified by path. If false, the downloaded artifacts will be extracted into individual named directories within the specified path.
          # merge-multiple: # optional, default is false
          # The GitHub token used to authenticate with the GitHub API. This is required when downloading artifacts from a different repository or from a different workflow run. If this is not specified, the action will attempt to download artifacts from the current repository and the current workflow run.
          # github-token: # optional
          # The repository owner and the repository name joined together by "/". If github-token is specified, this is the repository that artifacts will be downloaded from.
          # repository: # optional, default is ${{ github.repository }}
          # The id of the workflow run where the desired download artifact was uploaded from. If github-token is specified, this is the run that artifacts will be downloaded from.
          # run-id: # optional, default is ${{ github.run_id }}

      - name: List downloaded artifacts
        run: ls -la .github/artifacts

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: "1:296310144448:android:7e312254b40b06f99d5c25"
          # Content of service credentials file
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }} # optional
          # Artifact to upload (.apk or .ipa)
          file: ".github/artifacts/uploaded-android-app.apk"
          # file: "build/app/outputs/flutter-apk/app-release.apk"
          # Distribution groups
          groups: "codknox-testers" # optional
          # Distribution testers
          releaseNotes: "Test the core features of the app v(1.0.${{ github.run_number }})" # optional
          # Flag that can included to print verbose log output.
          debug: true




