name: Build and Analyze

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - pipeline

jobs:
  build-android:
    runs-on: macos-latest

    steps:
      - name: Basic Setup via Composite
        uses: ./.github/action_basic_setup/action.yml

      - name: Fetch plugins Flutter Project
        run: flutter pub get






