name: Build and Analyze

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - pipeline

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: 17
          #cache: 'gradle' (Error by Github Action: Invalid input)

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.27.3'

      #- name: Grant Gradle Permission to Github Workflow
      #  run: chmod +x android/gradlew

      - name: Fetch plugins Flutter Project
        run: flutter pub get

      - name: Build Android App
        run: flutter build apk --release

      - name: Push Releases to Github Repo
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}


